# Generated by Django 6.0.5 on 2026-05-07 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='currency',
            field=models.CharField(default='VND', max_length=3),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(default='Asia/Ho_Chi_Minh', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='tenant',
            unique_together={('name', 'owner')},
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['owner', 'is_active'], name='tenants_ten_owner_i_d26879_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['created_at'], name='tenants_ten_created_99c6ff_idx'),
        ),
    ]
