# Generated by Django 6.0.5 on 2026-05-11 00:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_currency_tenant_is_active_tenant_logo_and_more'),
        ('ticket', '0002_fishingpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hut',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Available', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huts', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
