# Generated by Django 6.0.5 on 2026-05-09 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('tenants', '0002_tenant_currency_tenant_is_active_tenant_logo_and_more'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ticket.session'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenant'),
        ),
    ]
